# Generated by Django 6.0.3 on 2026-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='public_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
