# Generated by Django 6.0.3 on 2026-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bite', '0002_restaurant_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
