# Generated by Django 6.0.3 on 2026-03-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bite', '0003_order_customer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(null=True),
        ),
    ]
